### ISSUE TITLE
from data_utils import plot_confusion_matrix

### ISSUE THREAD

**Issue by GlitteringAu** [sophiajw/HistAuGAN#1]
Hello，I want to replicate your experiential ，but no function **_plot_confusion_matrix_** in the data_utils , can you help me?

**Comment by sophiajw** [comment]
Hey, thanks for trying out the code!
I added the function in another file `utils.py`. Somehow, I deleted it when cleaning the code. Sorry for that!
Let me know if anything else doesn't work! I will add code and instructions to train the GAN soon!
Best
Sophia

**Comment by PeGunter** [comment]
OK,thank you for your timely reply，it's very kind of you!

**Comment by PeGunter** [comment]
Hello，I’m sorry to disturb you again.
I want to know if you have any set about the attribute **'weight'**,when I run the code,it points out 'Classifier' object has no attribute **'weight'**
`parser.add_argument('--weighted', action='store_true',help='model trains with weighted loss when flag is set')` in `main.py`
and when I set the weighted True  
` if weighted:  self.weight = 12.5`
`y_hat, y, pos_weight=self.weight.to(self.device)` in `model.py` points out the weight is 'float' object has no attribute 'to', did you have the problem?
Best
Jeter

**Comment by sophiajw** [comment]
Hey Jeter, sorry, same thing here. 
I tested the code again and uploaded the correct version!

**Comment by sophiajw** [comment]
btw the weight is introduced since I had many more healthy patches than tumor patches from the Camelyon17 annotations

**Comment by PeGunter** [comment]
Thank you,Sophia,I will try more to realize it.
