### ISSUE TITLE
Grid pattern in generated images

### ISSUE THREAD

**Issue by sofia-zimmer** [sophiajw/HistAuGAN#11]
Hi, I am using HistAuGAN for a personal project with histopathology images and I very pleased with the results I'am getting. The results for changing images domains is great. I've trained a model with my own data and the results are really good. However, I see there is a grid pattern constantly appearing in generated images. It doesn't seem to matter the input image size or resize for training or inference, this pattern seems to appear in every case. I wanted to know if you have seen something like it, and if you know what my be causing it. I'll leave some images below to show what I am talking about. 

![Screenshot from 2023-09-11 18-52-56](https://github.com/sophiajw/HistAuGAN/assets/144740107/2b11dc18-a4c4-4f45-be5a-368cbccd9c1b)
![Screenshot from 2023-09-11 18-52-40](https://github.com/sophiajw/HistAuGAN/assets/144740107/f56b1e5a-db86-4355-8f72-41e33937d82c)

![Screenshot from 2023-09-11 18-54-35](https://github.com/sophiajw/HistAuGAN/assets/144740107/91a42274-98b7-4166-939c-9f51a3df19f2)
![Screenshot from 2023-09-11 18-54-12](https://github.com/sophiajw/HistAuGAN/assets/144740107/7577a96e-fcf4-46ea-8ed6-e544aeeffb54)

Thank you!

**Comment by sophiajw** [comment]
Hey Sofia, 
thanks for trying it out and posting this! It is a common artifact in GANs from the transposed convolutions (nn.ConvTranspose2d). I could improve on this issue with reasonable results by adding another convolutional layer at the end of the generator in `networks.py`. The results look nicer with that, especially on white gaps or background (like in your 3rd image). Performance-wise the grid pattern didn't matter too much, in my experience. 
Best
Sophia

**Comment by sofia-zimmer** [comment]
Sophia, thank you very much for your reply. I'll try your suggestion!
