### ISSUE TITLE
isDcontent option removed

### ISSUE THREAD

**Issue by navajain19** [sophiajw/HistAuGAN#5]
Hello, I am trying to retrain the HistAuGAN model using my dataset but get the following error:

`--- train ---
Traceback (most recent call last):
  File "/home/ec2-user/insitro/core/HistAuGAN/histaugan/train.py", line 115, in <module>
    main()
  File "/home/ec2-user/insitro/core/HistAuGAN/histaugan/train.py", line 78, in main
    if opts.isDcontent:
AttributeError: 'Namespace' object has no attribute 'isDcontent'`

But from this [https://github.com/sophiajw/HistAuGAN/commit/86138217f86c3b99c83f8942a5058b8f5f38a3be#diff-2d9e4313dddbe55fe9c274ee[…]1f88f61b7f5141472bd0b60445a713](https://github.com/sophiajw/HistAuGAN/commit/86138217f86c3b99c83f8942a5058b8f5f38a3be#diff-2d9e4313dddbe55fe9c274ee6f6b479ef91f88f61b7f5141472bd0b60445a713) it looks like the isDcontent parameter was removed. Please let me know how I should proceed. Thanks!

**Comment by sophiajw** [comment]
hey, yes, I removed the option from the original code since for this project the content discriminator is always needed.
it should work now, I tested it.
sorry for the mistake!
